AUGMENTATION:
  BRIGHTNESS: false
  BRIGHTNESS_MAX_DELTA: 0.8
  CONTRAST: false
  CONTRAST_MAX_DELTA: 0.8
  HUE: false
  HUE_MAX_DELTA: 0.2
  RANDOM_CROP: false
  RANDOM_FLIP: true
  SATURATION: false
  SATURATION_MAX_DELTA: 0.8
  STRENGTH: 1.0
  COLOR_NORM: false
  COLOR_JITTER: false
  GRAYSCALE: false
DATA:
  ADDITION_TRAINSET: false
  CONSISTENT_OFFSET: 0.2
  CONTEXT_STRIDE: 2
  FRACTION: 1.0
  FRAME_LABELS: true
  NUM_CONTEXTS: 1
  NUM_WORKERS: 4
  SAMPLE_ALL_STRIDE: 1
  SAMPLING_REGION: 1.5
  SAMPLING_STRATEGY: time_augment
  TRAIN_NAME: long_train_label
  TEST_NAME: long_test_with_assumed_long_standard_label
  SKELETON_VIDEO: true
DATASETS:
- pouring
EVAL:
  BATCH_SIZE: 1
  CLASSIFICATION_FRACTIONS:
  - 0.1
  - 0.5
  - 1.0
  FRAMES_PER_BATCH: 1000
  KENDALLS_TAU_COMPUTE_LABELS: 0
  KENDALLS_TAU_DISTANCE: sqeuclidean
  KENDALLS_TAU_STRIDE: 2
  NUM_FRAMES: 240
  RETRIEVAL_KS:
  - 5
  - 10
  - 15
  TASKS:
  - kendalls_tau
  - retrieval
  VAL_INTERVAL: 50
IMAGE_SIZE: 224
LOGDIR: /home/c1l1mo/projects/VideoAlignment/result/scl_skating_long_skeleton
LOGGING:
  REPORT_INTERVAL: 20
MAX_TEMPERATURE: 0.1
MODEL:
  ENCODER:
    TYPE: ResNet
  EMBEDDER_MODEL:
    EMBEDDING_SIZE: 128
    FC_DROPOUT_RATE: 0.1
    HIDDEN_SIZE: 256
    NUM_LAYERS: 3
  EMBEDDER_TYPE: transformer
  L2_NORMALIZE: true
  PROJECTION: true
  PROJECTION_HIDDEN_SIZE: 512
  PROJECTION_SIZE: 128
  TRAIN_BASE: frozen
NUM_GPUS: 1
OPTIMIZER:
  GRAD_CLIP: 10
  LR:
    DECAY_TYPE: cosine
    FINAL_LR: 0.0
    INITIAL_LR: 0.0001
    NUM_WARMUP_STEPS: 1
    WARMUP_LR: 0.0001
  TYPE: AdamOptimizer
  WEIGHT_DECAY: 1.0e-05
PATH_TO_DATASET: NACL/1_jumps
SCL:
  LABEL_VARIENCE: 10.0
  NEGATIVE_TYPE: single_noself
  POSITIVE_TYPE: gauss
  POSITIVE_WINDOW: 5
  SOFTMAX_TEMPERATURE: 0.1
SSL: true
TCC:
  CYCLE_LENGTH: 2
  FRACTION: 1.0
  HUBER_DELTA: 0.1
  LABEL_SMOOTHING: 0.1
  LOSS_TYPE: regression_mse_var
  NORMALIZE_INDICES: true
  SIMILARITY_TYPE: l2
  SOFTMAX_TEMPERATURE: 0.1
  VARIANCE_LAMBDA: 0.001
TRAIN:
  BATCH_SIZE: 2
  MAX_EPOCHS: 500
  NUM_FRAMES: 50
  SCL_BATCH_SIZE: 10
TRAINING_ALGO: scl
VARIANCE_LAMBDA: 0.001
VISUALIZATION_DIR: /home/c1l1mo/projects/VideoAlignment/result/scl_skating_long_skeleton/visualization
